name = "fileshare"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "LINK", id = "4431547ac72145b1ba194f9f1c01fc5f",preview_id='4431547ac72145b1ba194f9f1c01fc5f'}
]
[site]
bucket = "./static/dist"
